name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: npx cypress run

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          architecture: x64

      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies  
        run: npm install

      - name: Run e2e tests
        run: ${{ github.event.inputs.cli }}

        
      - name: Publish Allure reports
        run: |
          npx run allure:generate
          npx run allure:report

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: allure-reports
          path: allure-report
