name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: npx cypress run --env allure=true

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          architecture: x64

      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: Create allure-results/history directory
        run: mkdir -p allure-results/history

      - name: Install dependencies  
        run: npm install

      - name: Run e2e tests
        run: ${{ github.event.inputs.cli }}

  allure-pr:
    name: Generate and Publish Allure Report
    runs-on: ubuntu-latest
    needs: cypress-electron-tests
    steps:
      - uses: actions/checkout@v2       

      - name: Create allure-results/history directory
        run: mkdir -p allure-results/history

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 1
